# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Goodbye World"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: |
      echo "hello world" > ~/output.txt
      npm run lint
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -run: npm run test
      - attach_workspace:
          at: ~/
      - sayhello

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test